### ISSUE TITLE
(not equals) Matching Operations is not working properly

### ISSUE THREAD

**Issue by asfor94** [apimastery/APISimulator#11]
Dear @apisim ,
Am trying to do some matching operations using equals and some other ones you can find attached my sample simulation.
The simulation should be done as below:
- when you send request without "OTP" it give a response.
- when you send request with "OTP" with specific value it should give another response.
- when you send request with "OTP" with specific value it should give another response.
- otherwise it should give a generic response.
kindly test it and feedback.

[apisim.yaml.txt](https://github.com/apimastery/APISimulator/files/6552413/apisim.yaml.txt)

**Comment by apisim** [comment]
Hi @asfor94,

We confirmed that in some cases there is a problem with the `not equals` matching operation.

A patched version of API Simulator is available here:
ZIP: https://apisimulator.io/downloads/apisimulator-http-1.10-RC1-distro.zip
TAR: https://apisimulator.io/downloads/apisimulator-http-1.10-RC1-distro.tar.gz

Those downloads also include the enablement of TLS versions 1.0, 1.1, as well as 1.3 (in addition to the previously "default" 1.2).

Notice that those Release Candidate versions will be removed from the download area in the future.

Let us know if the patch fixes the problem.

Happy API Simulating!

**Comment by asfor94** [comment]
Hi @apisim ,
So it is new patched version will you apply it in the website version also? 
I will check it and feed you back soon.

**Comment by apisim** [comment]
Hi @asfor94,

> So it is new patched version will you apply it in the website version also?

Yes. The [download page](https://apisimulator.io/download/) now has links to the 1.10-RC1 version.

**Comment by asfor94** [comment]
**Dear @apisim ,**
I had test the new version with the above sample that I had raised earlier and it is working properly now.
Thanks for your support, we will test it again with many conditions later and will feed you back in case we faced any issue.

**Comment by apisim** [comment]
Thank you, @asfor94 !
