### ISSUE TITLE
Consider using `Eclipse Temurin` and `Alpine` instead

### ISSUE THREAD

**Issue by x80486** [apimastery/APISimulator#19]
Currently the `Docker` images uses `Debian 11 (bullseye)` and `OpenJDK`.

A better alternative is to move towards `Eclipse Temurin` — and probably reduce the image footprint by using `Alpine` instead of `Debian`.

**Comment by x80486** [comment]
I can definitely help with this one :partying_face:

Also, both images could be published, although it wouldn't make much sense for an application because usually people don't use this image as a base for other images.

**Comment by apisim** [comment]
API Simulator's "official" Docker image used to be based on Alpine. This [blog article](https://apisimulator.io/run-docker-containers-non-root-users-random-user-ids/) from 2017 uses the Dockerfile of one of them in the examples. If I recall, though, there were compatibility issues at some point with netty-tcnative.

Given that the [OpenJDK Docker images](https://hub.docker.com/_/openjdk) have been deprecated as of recently, [eclipse-temurin](https://hub.docker.com/_/eclipse-temurin) base images make sense. Looking at the alternatives, the next "official" API Simulator Docker image will probably be based on an `Eclipse Temurin` image, indeed.

Thank you for the suggestions, @x80486!

**Comment by x80486** [comment]
Closed via 5ecd2d7

**Comment by apisim** [comment]
Thanks, @x80486!
Yep - the official image for API Simulator v1.11 is now based on Eclipse Temurin. BTW - there was a later commit to switch Java 19 to Java 11 - there are users that use the image for running simulations with JavaScript for scripting.
