### ISSUE TITLE
Folder organization and 404 on simlet

### ISSUE THREAD

**Issue by justinezahiri** [apimastery/APISimulator#23]
Our simlets are organized in folders. 

We have two folders named : 

`api-simulator/simlets/register/check-reference`
`api-simulator/simlets/reset-credentials/check-reference`

and we get a 404 (API Simulator doesn't find a simlet for...") on the first one. It works fine when we rename one of them. 
We think it's an issue because our routes in our simlet.yaml are diferent.

**Comment by apisim** [comment]
Hi @justinezahiri,

Thank you for bringing this up!

I was able to recreate the issue. This is from before the support for the all-in-one configuration - the directory name is assumed to be the simlet's name even if there's `simlet` element.

This should be addressed in the next release.

Happy API Simulating!

**Comment by justinezahiri** [comment]
Thank you for your prompt response :)

**Comment by apisim** [comment]
Fixed in v1.12. The [documentation](https://apisimulator.io/docs/1.12/standalone-api-simulator/api-simulation-configuration.html#directory-per-simlet) was also updated:

> The name of the directory with the simlet.yaml file becomes the name of the simlet unless simlet.yaml specifies the simlet name in the simlet element. As a good practice, always specify the simlet name in the simlet element. You must do that when a simulation has directories with the same name or otherwise one simlet definition will overwrite another.

Please verify when you have a chance and feel free to reopen the issue, if needed.
Thanks!
