### ISSUE TITLE
Short-Circuit Use of External Files

### ISSUE THREAD

**Issue by x80486** [apimastery/APISimulator#5]
While reading the [Using External Files](https://apisimulator.io/docs/1.7/standalone-api-simulator/api-simulation-configuration.html#using-external-files) I was under the impression that `simlets.path` will resolve to the _actual running_ simulation path — now I know that's not the case :smirk:

I'm aware that it's not a big deal, but it would be great if there is a variable like those (e.g.: `simlet.path`) that refers to the actual running simulation/simlet. Basically, the variable can resolve to the `PWD` of a given `simlet.yaml` that's being run/resolved when a request matches it.

**Comment by apisim** [comment]
Right...`simlets.path` resolves to the directory called `simlets` under the simulation's directory. We've actually heard this before from people who like to organize the simlets and their external files, especially for simulations with larger number of simlets. Noted, @x80486

**Comment by apisim** [comment]
Implemented and released with v1.8.

**Comment by x80486** [comment]
All right! Thank you so much! I'll test this one as soon as I can!

**Comment by x80486** [comment]
This is working fine according to the [documentation](https://apisimulator.io/docs/1.8/standalone-api-simulator/api-simulation-configuration.html#using-external-files).
